### ISSUE TITLE
Old microsoft video with lots of detail about design of MSVC's PGO

### ISSUE THREAD

**Issue by fsfod** [zamazan4ik/awesome-pgo#2]
There's an old hour long Microsoft video that has interviews with different MSVC compiler backend engineers, that goes into lots of detail about how MSVC's PGO works that's probably worth including somewhere on the page.  [GoingNative 12: C++ at Build 2012, Inside Profile Guided Optimization](https://learn.microsoft.com/en-us/shows/c9-goingnative/c9goingnative-12-c-build-2012-inside-profile-guided-optimization).

**Comment by zamazan4ik** [comment]
Thanks a lot! I will add this video to the repo. My only concern is that the video is a bit old - things have changed on the MSVC side in PGO, I guess. Anyway, since for MSVC is quite difficult to find materials - great finding.
