### ISSUE TITLE
Useful links: Slides about PGO: link (in Russian) 404

### ISSUE THREAD

**Issue by kotofos** [zamazan4ik/awesome-pgo#4]
URL for Slides about PGO: link (in Russian) returning 404. At least from Poland.

https://assets.ctfassets.net/oxjq45e8ilak/41KrMkvfzUDEu6MDOEQL7q/dd4575d45a19aef27eebae411faa7952/PGO-___________________________________________________________.pdf

```
{
  "sys": {
    "type": "Error",
    "id": "NotFound"
  },
  "message": "The resource could not be found."
}
```

**Comment by zamazan4ik** [comment]
Yes, the original PDF link from the description for [this](https://www.youtube.com/watch?v=CvbIPGSnes8) is broken. Thank you for the report. I'll try to ask the author to re-upload the slides to another place.

**Comment by kpdev** [comment]
Please check this one )
https://github.com/kpdev/rnd_code_blog_utils/blob/main/util/PGO_CPP_RUS_15-11-2021.pdf
