### ISSUE TITLE
Misleading statement on GraalVM AoT compilation support in `awesome-pgo` article.

### ISSUE THREAD

**Issue by dmitry-j-mikhin** [zamazan4ik/awesome-pgo#9]
**Issue:** Misleading statement on GraalVM AoT compilation support in `awesome-pgo` article.

**Description:**
In the article at https://github.com/zamazan4ik/awesome-pgo/blob/main/article/article.md, the statement:

> "By the way, GraalVM supports AoT compilation mode for Python, Ruby, R, Javascript (and maybe something). So you can try to apply GraalVM-flavoured PGO on them too (not many people tried to do such things so bugs should be expected)."

appears to be inaccurate regarding GraalVM's AoT compilation capabilities for Ruby. According to the [discussion in the TruffleRuby GitHub repository](https://github.com/oracle/truffleruby/discussions/2853#discussioncomment-4893241):

> "Note that Native Image cannot compile Ruby code ahead-of-time, unlike Java code. TruffleRuby Native is the TruffleRuby interpreter AOT-compiled but no Ruby code is AOT-compiled; it is still interpreted + JITed."

This implies that while GraalVM’s Native Image can AoT-compile the TruffleRuby interpreter itself, it does not support AoT compilation of Ruby code specifically, which is still interpreted and JIT-compiled.

**Suggested Resolution:**
Update the article to clarify that GraalVM AoT compilation support varies by language. Ruby, for example, does not benefit from full AoT compilation of user code, which remains JIT-compiled. This will help manage reader expectations and avoid confusion around GraalVM's capabilities for different languages.

**Comment by zamazan4ik** [comment]
Yep, I agree with your comment. Removed this paragraph from the article. Thanks!
